import { ARM5E } from "../config.js";
export const UI = {};

UI.METAGAME = [
  "ability",
  "virtue",
  "flaw",
  "quality",
  "inferiority",
  "baseEffect",
  "spell",
  "armor",
  "weapon",
  "enchantment",
  "book",
  "power"
];

UI.STYLES = {
  FILTER_ACTIVE: 'style="text-shadow: 0 0 5px maroon"',
  STANDARD_ART: 'style="border: 0px"',
  DEFICIENT_ART: 'style="border: 0px; box-shadow: 0 0 10px darkslateblue"',
  PUISSANT_ART: 'style="border: 0px; box-shadow: 0 0 10px blue"',
  AFINITY_ART: 'style="border: 0px; box-shadow: 0 0 10px maroon"',
  COMBO_ART: 'style="border: 0px; box-shadow: 0 0 10px purple"',
  STANDARD_ABILITY: 'style="border: 0px;"',
  PUISSANT_ABILITY: 'style="box-shadow: 0 0 10px blue"',
  AFFINITY_ABILITY: 'style="box-shadow: 0 0 10px maroon"',
  COMBO_ABILITY: 'style="box-shadow: 0 0 10px purple"',
  CALENDAR_BUSY: "busy",
  CALENDAR_CURRENT: "current",
  CALENDAR_CONFLICT: "conflict"
};

export const ARM5E_DEFAULT_ICONS = {};

// default icons

ARM5E_DEFAULT_ICONS.MONO = {
  weapon: "icons/svg/sword.svg",
  armor: "icons/svg/statue.svg",
  spell: "icons/svg/explosion.svg",
  vis: "icons/svg/daze.svg",
  book: "icons/svg/book.svg",
  virtue: `systems/${ARM5E.SYSTEM_ID}/assets/icons/upgraded-magic.svg`,
  flaw: `systems/${ARM5E.SYSTEM_ID}/assets/icons/base-magic.svg`,
  ability: "icons/svg/aura.svg",
  abilityFamiliar: "icons/svg/aura.svg",
  diaryEntry: "icons/svg/sun.svg",
  power: "icons/svg/tower.svg",
  powerFamiliar: "icons/svg/tower.svg",
  speciality: "icons/svg/obelisk.svg",
  distinctive: "icons/svg/target.svg",
  sanctumRoom: "icons/svg/temple.svg",
  magicItem: "icons/svg/mage-shield.svg",
  personalityTrait: "icons/svg/aura.svg",
  reputation: "icons/svg/angel.svg",
  inhabitant: "icons/svg/city.svg",
  habitantMagi: "icons/svg/mountain.svg",
  habitantCompanion: "icons/svg/castle.svg",
  habitantSpecialists: "icons/svg/city.svg",
  habitantHabitants: "icons/svg/village.svg",
  habitantHorses: "icons/svg/bridge.svg",
  habitantLivestock: "icons/svg/windmill.svg",
  possessionsCovenant: "icons/svg/barrel.svg",
  visSourcesCovenant: "icons/svg/ruins.svg",
  visStockCovenant: "icons/svg/chest.svg",
  magicalEffect: "icons/svg/up.svg",
  baseEffect: "icons/svg/down.svg",
  calendarCovenant: "icons/svg/clockwork.svg",
  incomingSource: "icons/svg/regen.svg",
  laboratoryText: `systems/${ARM5E.SYSTEM_ID}/assets/icons/journal-book.svg`,
  magicCodex: "icons/commodities/materials/parchment-secrets.webp",
  covenant: "icons/svg/castle.svg",
  npc: "icons/svg/mystery-man-black.svg",
  laboratory: "icons/svg/tower.svg",
  enchantment: "icons/svg/daze.svg",
  labCovenant: "icons/svg/tower.svg",
  container: "icons/svg/chest.svg"
};
ARM5E_DEFAULT_ICONS.COLOR = {
  weapon: "icons/weapons/swords/greatsword-crossguard-silver.webp",
  armor: "icons/equipment/chest/breastplate-scale-grey.webp",
  spell: "icons/magic/light/explosion-star-glow-blue-purple.webp",
  vis: "icons/magic/light/orbs-firefly-hand-yellow.webp",
  item: "icons/sundries/survival/rope-coiled-tan.webp",
  book: "icons/sundries/books/book-tooled-eye-gold-red.webp",
  virtue: "icons/magic/light/explosion-star-glow-silhouette.webp",
  flaw: "icons/magic/control/silhouette-hold-change-blue.webp",
  // "flaw": "icons/magic/unholy/silhouette-evil-horned-giant.webp",
  ability: "icons/skills/trades/woodcutting-logging-axe-stump.webp",
  abilityFamiliar: "icons/creatures/mammals/deer-antlers-glowing-blue.webp",
  diaryEntry: "icons/sundries/documents/document-sealed-signatures-red.webp",
  power: "icons/creatures/abilities/dragon-fire-breath-orange.webp",
  powerFamiliar: "icons/creatures/abilities/wolf-howl-moon-purple.webp",
  speciality: "icons/skills/trades/construction-carpentry-hammer.webp",
  distinctive: "icons/sundries/flags/banner-symbol-sun-gold-red.webp",
  magicItem: "icons/weapons/staves/staff-ornate-red.webp",
  personalityTrait: "icons/skills/social/intimidation-impressing.webp",
  reputation: "icons/skills/social/diplomacy-handshake.webp",
  habitantCompanion: "icons/environment/people/cleric-grey.webp",
  habitantSpecialists: "icons/environment/people/commoner.webp",
  habitantHabitants: "icons/environment/people/group.webp",
  habitantHorses: "icons/environment/creatures/horse-brown.webp",
  habitantLivestock: "icons/environment/creatures/horses.webp",
  possessionsCovenant: "icons/commodities/currency/coins-plain-pouch-gold.webp",
  visSourcesCovenant: "icons/environment/wilderness/arch-stone.webp",
  visStockCovenant: "icons/commodities/currency/coin-oval-rune-copper.webp",
  incomingSource: "icons/commodities/currency/coins-plain-pouch-gold.webp",
  laboratoryText: "icons/sundries/documents/blueprint-recipe-alchemical.webp",
  magicalEffect: "icons/sundries/documents/document-symbol-lightning-brown.webp",
  baseEffect: "icons/sundries/scrolls/scroll-symbol-eye-brown.webp",
  enchantment: "icons/magic/symbols/runes-etched-steel-blade.webp",
  labCovenant: "icons/tools/laboratory/vials-blue-pink.webp",
  // Actors
  covenant: "icons/environment/settlement/wizard-castle.webp",
  magicCodex: "icons/commodities/materials/parchment-secrets.webp",
  npc: "icons/svg/mystery-man-black.svg",
  laboratory: "icons/tools/laboratory/vials-blue-pink.webp",
  container: "icons/containers/chest/chest-elm-steel-brown.webp"
};

export const ACTIVITIES_DEFAULT_ICONS = {
  MONO: {
    none: `systems/${ARM5E.SYSTEM_ID}/assets/icons/activities/Diary.svg`,
    inventSpell: `systems/${ARM5E.SYSTEM_ID}/assets/icons/activities/InventSpell.svg`,
    learnSpell: `systems/${ARM5E.SYSTEM_ID}/assets/icons/activities/LearnSpell.svg`,
    adventuring: `systems/${ARM5E.SYSTEM_ID}/assets/icons/activities/Adventuring.svg`,
    exposure: `systems/${ARM5E.SYSTEM_ID}/assets/icons/activities/Exposure.svg`,
    practice: `systems/${ARM5E.SYSTEM_ID}/assets/icons/activities/Practice.svg`,
    training: `systems/${ARM5E.SYSTEM_ID}/assets/icons/activities/Training.svg`,
    teaching: `systems/${ARM5E.SYSTEM_ID}/assets/icons/activities/Teaching.svg`,
    hermeticApp: `systems/${ARM5E.SYSTEM_ID}/assets/icons/activities/Diary.svg`,
    childhood: `systems/${ARM5E.SYSTEM_ID}/assets/icons/activities/HermeticApp.svg`,
    laterLife: `systems/${ARM5E.SYSTEM_ID}/assets/icons/activities/LaterLife.svg`,
    laterLifeMagi: `systems/${ARM5E.SYSTEM_ID}/assets/icons/activities/LaterLifeMagi.svg`,
    reading: `systems/${ARM5E.SYSTEM_ID}/assets/icons/activities/Reading.svg`,
    writing: `systems/${ARM5E.SYSTEM_ID}/assets/icons/activities/Writing.svg`,
    visExtraction: `systems/${ARM5E.SYSTEM_ID}/assets/icons/activities/VisExtraction.svg`,
    lab: `systems/${ARM5E.SYSTEM_ID}/assets/icons/activities/Lab.svg`,
    aging: `systems/${ARM5E.SYSTEM_ID}/assets/icons/activities/Aging.svg`,
    visStudy: `systems/${ARM5E.SYSTEM_ID}/assets/icons/activities/VisStudy.svg`,
    recovery: `systems/${ARM5E.SYSTEM_ID}/assets/icons/recovery/healed.png`,
    investigateItem: "icons/svg/eye.svg",
    resourceOutput: `systems/${ARM5E.SYSTEM_ID}/assets/icons/activities/expense.svg`,
    resourceInput: `systems/${ARM5E.SYSTEM_ID}/assets/icons/activities/profit.svg`
  },
  COLOR: {
    none: "icons/sundries/documents/document-sealed-signatures-red.webp",
    inventSpell: "icons/sundries/documents/document-letter-blue.webp",
    learnSpell: "icons/sundries/documents/blueprint-recipe-magic.webp",
    adventuring: "icons/tools/navigation/map-marked-brown.webp",
    exposure: "icons/magic/perception/eye-tendrils-web-purple.webp",
    practice: "icons/environment/people/archer.webp",
    training: "icons/skills/movement/arrow-upward-blue.webp",
    teaching: "icons/skills/movement/arrows-up-trio-red.webp",
    hermeticApp: "icons/skills/trades/academics-investigation-study-blue.webp",
    childhood: "icons/magic/time/day-night-sunset-sunrise.webp",
    laterLife: "icons/magic/time/hourglass-brown-orange.webp",
    laterLifeMagi: "icons/magic/symbols/runes-star-blue.webp",
    reading: "icons/sundries/books/book-open-red.webp",
    writing: "icons/sundries/books/book-open-purple.webp",
    visExtraction: "icons/skills/toxins/bottle-open-vapors-pink.webp",
    lab: "icons/tools/laboratory/vials-blue-pink.webp",
    aging: "icons/sundries/misc/hourglass-wood.webp",
    visStudy: "icons/skills/toxins/bottle-open-vapors-pink.webp",
    recovery: "icons/magic/life/cross-explosion-burst-green.webp",
    longevityRitual: "icons/consumables/potions/bottle-pear-corked-pink.webp",
    minorEnchant: "icons/skills/trades/smithing-anvil-silver-red.webp",
    investigateItem: "icons/tools/scribal/magnifying-glass.webp",
    resourceOutput: `systems/${ARM5E.SYSTEM_ID}/assets/icons/activities/expense.svg`,
    resourceInput: `systems/${ARM5E.SYSTEM_ID}/assets/icons/activities/profit.svg`
  }
};

export const INHABITANTS_DEFAULT_ICONS = {
  MONO: {
    magi: "icons/svg/mountain.svg",
    companions: "icons/svg/castle.svg",
    grogs: "icons/svg/combat.svg",
    craftsmen: "icons/svg/city.svg",
    specialists: "icons/svg/city.svg",
    dependants: "icons/svg/village.svg",
    servants: "icons/svg/village.svg",
    teamsters: "icons/svg/village.svg",
    horses: "icons/svg/bridge.svg",
    livestock: "icons/svg/windmill.svg"
  },
  COLOR: {
    magi: "icons/svg/mountain.svg",
    companions: "icons/svg/castle.svg",
    grogs: "icons/skills/melee/sword-shield-stylized-white.webp",
    craftsmen: "icons/environment/people/commoner.webp",
    specialists: "icons/environment/people/commoner.webp",
    dependants: "icons/environment/people/group.webp",
    servants: "icons/environment/people/group.webp",
    teamsters: "icons/environment/people/group.webp",
    horses: "icons/environment/creatures/horse-brown.webp",
    livestock: "icons/environment/creatures/horses.webp"
  }
};

export const VIRTUESFLAWS_DEFAULT_ICONS = {
  MONO: {
    hermetic: `systems/${ARM5E.SYSTEM_ID}/assets/icons/VF/hermetic.svg`,
    supernatural: `systems/${ARM5E.SYSTEM_ID}/assets/icons/VF/supernatural.svg`,
    social: `systems/${ARM5E.SYSTEM_ID}/assets/icons/VF/social.svg`,
    socialWestern: `systems/${ARM5E.SYSTEM_ID}/assets/icons/VF/social.svg`,
    socialEastern: `systems/${ARM5E.SYSTEM_ID}/assets/icons/VF/social.svg`,
    socialJewish: `systems/${ARM5E.SYSTEM_ID}/assets/icons/VF/social.svg`,
    socialIslamic: `systems/${ARM5E.SYSTEM_ID}/assets/icons/VF/social.svg`,
    socialHibernia: `systems/${ARM5E.SYSTEM_ID}/assets/icons/VF/social.svg`,
    socialIberia: `systems/${ARM5E.SYSTEM_ID}/assets/icons/VF/social.svg`,
    socialNorthAfrica: `systems/${ARM5E.SYSTEM_ID}/assets/icons/VF/social.svg`,
    socialPersia: `systems/${ARM5E.SYSTEM_ID}/assets/icons/VF/social.svg`,
    socialProvencal: `systems/${ARM5E.SYSTEM_ID}/assets/icons/VF/social.svg`,
    generalVirtue: `systems/${ARM5E.SYSTEM_ID}/assets/icons/VF/generalVirtue.svg`,
    generalFlaw: `systems/${ARM5E.SYSTEM_ID}/assets/icons/VF/generalFlaw.svg`,
    personality: `systems/${ARM5E.SYSTEM_ID}/assets/icons/VF/personality.svg`,
    story: `systems/${ARM5E.SYSTEM_ID}/assets/icons/VF/story.svg`,
    child: `systems/${ARM5E.SYSTEM_ID}/assets/icons/VF/child.svg`,
    heroic: `systems/${ARM5E.SYSTEM_ID}/assets/icons/VF/heroic.svg`,
    tainted: `systems/${ARM5E.SYSTEM_ID}/assets/icons/VF/tainted.svg`
  }
};

export const ABILITIES_DEFAULT_ICONS = {
  MONO: {
    animalHandling: `systems/${ARM5E.SYSTEM_ID}/assets/icons/abilities/animalHandling.svg`,
    areaLore: `systems/${ARM5E.SYSTEM_ID}/assets/icons/abilities/areaLore.svg`,
    athletics: `systems/${ARM5E.SYSTEM_ID}/assets/icons/abilities/athletics.svg`,
    awareness: `systems/${ARM5E.SYSTEM_ID}/assets/icons/abilities/awareness.svg`,
    bargain: `systems/${ARM5E.SYSTEM_ID}/assets/icons/abilities/bargain.svg`,
    brawl: `systems/${ARM5E.SYSTEM_ID}/assets/icons/abilities/brawl.svg`,
    carouse: `systems/${ARM5E.SYSTEM_ID}/assets/icons/abilities/carouse.svg`,
    charm: `systems/${ARM5E.SYSTEM_ID}/assets/icons/abilities/charm.svg`,
    chirurgy: `systems/${ARM5E.SYSTEM_ID}/assets/icons/abilities/chirurgy.svg`,
    concentration: `systems/${ARM5E.SYSTEM_ID}/assets/icons/abilities/concentration.svg`,
    craft: `systems/${ARM5E.SYSTEM_ID}/assets/icons/abilities/craft.svg`,
    etiquette: `systems/${ARM5E.SYSTEM_ID}/assets/icons/abilities/etiquette.svg`,
    folkKen: `systems/${ARM5E.SYSTEM_ID}/assets/icons/abilities/folkKen.svg`,
    guile: `systems/${ARM5E.SYSTEM_ID}/assets/icons/abilities/guile.svg`,
    hunt: `systems/${ARM5E.SYSTEM_ID}/assets/icons/abilities/hunt.svg`,
    intrigue: `systems/${ARM5E.SYSTEM_ID}/assets/icons/abilities/intrigue.svg`,
    leadership: `systems/${ARM5E.SYSTEM_ID}/assets/icons/abilities/leadership.svg`,
    legerdemain: `systems/${ARM5E.SYSTEM_ID}/assets/icons/abilities/legerdemain.svg`,
    livingLanguage: `systems/${ARM5E.SYSTEM_ID}/assets/icons/abilities/livingLanguage.svg`,
    music: `systems/${ARM5E.SYSTEM_ID}/assets/icons/abilities/music.svg`,
    organizationLore: `systems/${ARM5E.SYSTEM_ID}/assets/icons/abilities/organizationLore.svg`,
    profession: `systems/${ARM5E.SYSTEM_ID}/assets/icons/abilities/profession.svg`,
    ride: `systems/${ARM5E.SYSTEM_ID}/assets/icons/abilities/ride.svg`,
    stealth: `systems/${ARM5E.SYSTEM_ID}/assets/icons/abilities/stealth.svg`,
    survival: `systems/${ARM5E.SYSTEM_ID}/assets/icons/abilities/survival.svg`,
    swim: `systems/${ARM5E.SYSTEM_ID}/assets/icons/abilities/swim.svg`,
    teaching: `systems/${ARM5E.SYSTEM_ID}/assets/icons/abilities/teaching.svg`,
    artesLib: `systems/${ARM5E.SYSTEM_ID}/assets/icons/abilities/artesLib.svg`,
    law: `systems/${ARM5E.SYSTEM_ID}/assets/icons/abilities/law.svg`,
    deadLanguage: `systems/${ARM5E.SYSTEM_ID}/assets/icons/abilities/deadLanguage.svg`,
    medicine: `systems/${ARM5E.SYSTEM_ID}/assets/icons/abilities/medicine.svg`,
    philosophy: `systems/${ARM5E.SYSTEM_ID}/assets/icons/abilities/philosophy.svg`,
    theology: `systems/${ARM5E.SYSTEM_ID}/assets/icons/abilities/theology.svg`,
    hermeticCode: `systems/${ARM5E.SYSTEM_ID}/assets/icons/abilities/hermeticCode.svg`,
    dominionLore: `systems/${ARM5E.SYSTEM_ID}/assets/icons/abilities/dominionLore.svg`,
    faerieLore: `systems/${ARM5E.SYSTEM_ID}/assets/icons/abilities/faerieLore.svg`,
    finesse: `systems/${ARM5E.SYSTEM_ID}/assets/icons/abilities/finesse.svg`,
    infernalLore: `systems/${ARM5E.SYSTEM_ID}/assets/icons/abilities/infernalLore.svg`,
    magicLore: `systems/${ARM5E.SYSTEM_ID}/assets/icons/abilities/magicLore.svg`,
    magicTheory: `systems/${ARM5E.SYSTEM_ID}/assets/icons/abilities/magicTheory.svg`,
    parma: `systems/${ARM5E.SYSTEM_ID}/assets/icons/abilities/parma.svg`,
    penetration: `systems/${ARM5E.SYSTEM_ID}/assets/icons/abilities/penetration.svg`,
    martial: `systems/${ARM5E.SYSTEM_ID}/assets/icons/abilities/martial.svg`,
    bows: `systems/${ARM5E.SYSTEM_ID}/assets/icons/abilities/bows.svg`,
    singleWeapon: `systems/${ARM5E.SYSTEM_ID}/assets/icons/abilities/singleWeapon.svg`,
    greatWeapon: `systems/${ARM5E.SYSTEM_ID}/assets/icons/abilities/greatWeapon.svg`,
    trownWeapon: `systems/${ARM5E.SYSTEM_ID}/assets/icons/abilities/trownWeapon.svg`,
    animalKen: `systems/${ARM5E.SYSTEM_ID}/assets/icons/abilities/animalKen.svg`,
    dowsing: `systems/${ARM5E.SYSTEM_ID}/assets/icons/abilities/dowsing.svg`,
    enchantingMusic: `systems/${ARM5E.SYSTEM_ID}/assets/icons/abilities/enchantingMusic.svg`,
    entrancement: `systems/${ARM5E.SYSTEM_ID}/assets/icons/abilities/entrancement.svg`,
    magicSensitivity: `systems/${ARM5E.SYSTEM_ID}/assets/icons/abilities/magicSensitivity.svg`,
    premonitions: `systems/${ARM5E.SYSTEM_ID}/assets/icons/abilities/premonitions.svg`,
    secondSight: `systems/${ARM5E.SYSTEM_ID}/assets/icons/abilities/secondSight.svg`,
    senseHolyAndUnholy: `systems/${ARM5E.SYSTEM_ID}/assets/icons/abilities/senseHolyAndUnholy.svg`,
    shapeshifter: `systems/${ARM5E.SYSTEM_ID}/assets/icons/abilities/shapeshifter.svg`,
    wildernessSense: `systems/${ARM5E.SYSTEM_ID}/assets/icons/abilities/wildernessSense.svg`,
    enigma: `systems/${ARM5E.SYSTEM_ID}/assets/icons/abilities/enigma.svg`,
    faerieMagic: `systems/${ARM5E.SYSTEM_ID}/assets/icons/abilities/faerieMagic.svg`,
    heartbeast: `systems/${ARM5E.SYSTEM_ID}/assets/icons/abilities/heartbeast.svg`,
    verditiusMagic: `systems/${ARM5E.SYSTEM_ID}/assets/icons/abilities/verditiusMagic.svg`,
    cult: `systems/${ARM5E.SYSTEM_ID}/assets/icons/abilities/cult.svg`
  }
};

export const FLAVORS = {
  NEUTRAL: "Neutral",
  PLAYER: "PC",
  NPC: "NPC",
  BEAST: "Beast",
  LABORATORY: "Lab",
  COVENANT: "covenant",
  CODEX: "codex"
};
